.editorconfig

editor config to unify code style

---

ModelCatalogueCorePlugin/ModelCatalogueCoreGrailsPlugin.groovy
ModelCatalogueCorePlugin/grails-app/conf/ModelCatalogueCorePluginUrlMappings.groovy
ModelCatalogueCorePlugin/grails-app/controllers/org/modelcatalogue/core/DataModelController.groovy
ModelCatalogueCorePlugin/grails-app/services/org/modelcatalogue/core/DataClassService.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/export/inventory/DataClassToXlsxExporter.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/export/inventory/DataModelToXlsxExporter.groovy
ModelCatalogueCorePlugin/test/integration/org/modelcatalogue/core/export/inventory/DataModelToXlsxExporterSpec.groovy

Export of Data Model to Excel, fixes Met-958

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/catalogueElementProperties.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/catalogueElementView.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/detailSections.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/detailSections.coffee
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/a/DataClassWizardSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/c/DataTypeWizardSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/geb/AbstractModelCatalogueGebSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/geb/Common.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/geb/NavigatorCondition.groovy
ModelCatalogueFormsPlugin/grails-app/assets/javascripts/mc/core/forms/templates/formItem.tpl.html
ModelCatalogueFormsPlugin/grails-app/assets/javascripts/modelcatalogue/core/forms/forms.coffee

- fixes MET-978
@musketyr, please review :bomb:

Met 978 data type view improvements

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/catalogueElementProperties.coffee

@musketyr this was easy :rocket:

change columns of imports relationship

---

ModelCatalogueFormsPlugin/grails-app/assets/javascripts/mc/core/forms/templates/formItem.tpl.html

fix tooltip for form item regex

---

.gitignore
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/export/inventory/DataClassToXlsxExporter.groovy
ModelCatalogueCorePlugin/test/integration/org/modelcatalogue/core/export/inventory/DataClassToXlsxExporterSpec.groovy

@musketyr hope test won't fail... :tiger2:

Met 988 export xls depracated parents

---

ModelCatalogueCorePlugin/ModelCatalogueCoreGrailsPlugin.groovy
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/actions.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/modalPrompt.coffee
ModelCatalogueCorePlugin/grails-app/controllers/org/modelcatalogue/core/DataClassController.groovy
ModelCatalogueCorePlugin/grails-app/controllers/org/modelcatalogue/core/DataModelController.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/reports/ReportDescriptor.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/reports/ReportDescriptorBuilder.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/util/marshalling/AbstractMarshaller.groovy
ModelCatalogueCorePlugin/test/integration/org/modelcatalogue/core/reports/ReportsRegistryIntegrationSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/a/AssetWizardSpec.groovy
ModelCatalogueFormsPlugin/ModelCatalogueFormsPluginGrailsPlugin.groovy
ModelCatalogueGenomicsPlugin/ModelCatalogueGenomicsPluginGrailsPlugin.groovy

@musketyr happy merging :family:

Met 987 export asset name

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/templates/catalogueElementTreeviewItem.tpl.html
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/catalogueElementTreeviewItem.coffee
ModelCatalogueCorePlugin/test/js/modelcatalogue/core/ui/bs/catalogueElementTreeviewItem.spec.coffee

Do not merge this. It's not ready yet. :hourglass_flowing_sand:

Met 792 tree view relationship view

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/actions.coffee

@musketyr Is this what you've been expected? :point_left: 
I don't check this on server side, so you can basically hack that but I understood this to be fine...

MET-1007 export menu item is available only to ADMIN and ROLE_METADATA_CURATOR

---

ModelCatalogueGenomicsPlugin/ModelCatalogueGenomicsPluginGrailsPlugin.groovy
ModelCatalogueGenomicsPlugin/grails-app/conf/ModelCatalogueGenomicsUrlMappings.groovy
ModelCatalogueGenomicsPlugin/grails-app/controllers/org/modelcatalogue/core/genomics/GenomicsController.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/RareDiseaseDisorderListCsvExporter.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/RareDiseaseDisorderListCsvExporterSpec.groovy

new csv generation and also reverted the change Matous made in controller from 'creates asset' to 'creates link' as this seemed to have broken the functionality. The use of 'asset' seems to bring up a dialog - not sure if this is required for our cases.

ODA-840 Rare Disease Disorder List as CSV

---

ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/RareDiseaseDisorderListCsvExporter.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/RareDiseasesDocExporter.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/RareDiseaseDisorderListCsvExporterSpec.groovy

Formatting & other changes from story review

ODA-838,839,840 implement changes from business review

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/modals/templates/modalNewRelationship.tpl.html
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/modals/modalPromptDataElementEdit.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/modals/modalPromptNewRelationship.coffee

@musketyr I feel like this :ok_hand: to be reviewed :-)

Met 998 add relationship create

---

ModelCatalogueCorePluginTestApp/grails-app/conf/BootStrap.groovy

as there is a problem to be up to date with elasticsearch index

not using cached db when running the database

---

ModelCatalogueCorePluginTestApp/grails-app/conf/Config.groovy

using the timestamp in ElasticSearch data folder in dev and test mode

MET-1029 error showing my models in dev mode

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/actions.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/withClassificationCtrlMixin.coffee
ModelCatalogueCorePlugin/grails-app/controllers/org/modelcatalogue/core/AbstractCatalogueElementController.groovy

no longer shows create actions for finalized data models, instead of creating draft data model automatically shows error message if the data model is draft

MET-1016 added reference type to finalized model

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/states/index.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/util/MessagingClient.js
ModelCatalogueCorePluginTestApp/grails-app/views/index.gsp

- log again angular ui states
@musketyr to log or not to log, that is the question... :-D 🚔

set logProvider not to log when not in production

---

ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/CancerTypesCsvExporter.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/AbstractCancerTypesExporterSpec.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/CancerTypesCsvExporterSpec.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/CancerTypesJsonExporterSpec.groovy

At last got agreement on unified format - simplified tests/code to match

ODA-847 Cancer Types/Subtypes and Presentations CSV all in one csv

---

ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/CancerTypesJsonExporter.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/CancerTypesJsonExporterSpec.groovy

As for CSV story got agreement on unified json format for Subtypes & Presentations so simplified code/tests to match.
BTW. thanks for spec fix yesterday - I blame my still getting to grips with this Git process that feels like a fight every day :-)

ODA-846 Cancer Types and Presentations all in one json

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/infiniteTable.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/metadataEditor.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/utils/orderedMapEditor.coffee
ModelCatalogueCorePluginTestApp/grails-app/views/index.gsp

using $timeout instead of $scope.apply to prevent digest already in progress error
see e.g. http://stackoverflow.com/questions/22346990/why-is-using-ifscope-phase-scope-apply-an-anti-pattern
enabled strict DI mode

timeout instead of apply

---

ModelCatalogueCorePlugin/grails-app/controllers/org/modelcatalogue/core/DataClassController.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/publishing/changelog/ChangeLogDocxGenerator.groovy
ModelCatalogueCorePlugin/test/integration/org/modelcatalogue/core/publishing/changelog/ChangeLogDocxGeneratorSpec.groovy

renamed this in preparation of creating a standalone ChangeLog generator

ODA-833 preparing for changes to ChangeLog generator

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/utils/orderedMapEditor.coffee

- stop default event propagation when pasting to input
Always nice to learn new stuff 😶

MET-1024 fix safari copy paste

---

.gitignore
.travis.yml
ModelCatalogueCorePlugin/grails-app/domain/org/modelcatalogue/core/PrimitiveType.groovy
ModelCatalogueCorePlugin/grails-app/domain/org/modelcatalogue/core/ReferenceType.groovy
ModelCatalogueElasticSearchPlugin/grails-app/services/org/modelcatalogue/core/elasticsearch/ElasticSearchService.groovy

1. on reindex there were IndexAlreadyExistsException thrown very often but not catched properly
2. after that fixed creating document for primitive or reference type thrown LazyInitializationException as the dataClass or measurementUnit was not properly fetched

fixing the reindexing

---

ModelCatalogueGenomicsPlugin/ModelCatalogueGenomicsPluginGrailsPlugin.groovy
ModelCatalogueGenomicsPlugin/grails-app/conf/ModelCatalogueGenomicsUrlMappings.groovy
ModelCatalogueGenomicsPlugin/grails-app/controllers/org/modelcatalogue/core/genomics/GenomicsController.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/GelXlsStyles.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/RareDiseasePhenotypeChangeLogXlsExporter.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/AbstractRareDiseasesExporterSpec.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/RareDiseasePhenotypeChangeLogXlsExporterSpec.groovy

I expect to do further work on this code as part of a following related story but think it's good to get it in so  tester can have a look.
If you're interested you'll see I created a test for the method extractDeepElement() which shows where part of my issue lies - I'm sure I'll have to come back to this area.

ODA-833 XLS Change log for RD Phenotypes and clinical tests

---

ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/CancerTypesCsvExporter.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/AbstractCancerTypesExporterSpec.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/CancerTypesCsvExporterSpec.groovy

fix to add enums to output. Also I'm experimenting with comitting/pushing from Intellij...we'll see how that goes...

ODA-847 Cancer Types/Presentations/Subtypes CSV - enums fix

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/catalogueElementActions.coffee
ModelCatalogueCorePlugin/grails-app/services/org/modelcatalogue/core/ElementService.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/integration/obo/OboLoader.groovy
ModelCatalogueCorePlugin/test/integration/org/modelcatalogue/core/ElementServiceIntegrationSpec.groovy
ModelCatalogueCorePlugin/test/integration/org/modelcatalogue/core/HPOUpdatesSpec.groovy

to obsolete data class container

MET-956 move deprecated data elements and data classes

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/modals/modalPromptEditRelationship.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/modals/modalPromptNewRelationship.coffee

based on is example of such relationships

MET-950 better hints when the relationship requires same type

---

ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/CancerTypesCsvExporter.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/CancerTypesJsonExporter.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/AbstractCancerTypesExporterSpec.groovy
ModelCatalogueGenomicsPlugin/test/integration/org/modelcatalogue/gel/export/CancerTypesJsonExporterSpec.groovy

ODA-846 Cancer Types/Presentations/Subtypes JSON - enums fix

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/navigationRightActions.coffee

ODA-1107 do not show import action

---

ModelCatalogueFormsPlugin/grails-app/services/org/modelcatalogue/core/forms/ModelToFormExporterService.groovy

as it may violate the max 255 characters constraint

MET-1079 not appending the regexp to validation error

---

ModelCatalogueElasticSearchPlugin/grails-app/services/org/modelcatalogue/core/elasticsearch/ElasticSearchService.groovy

before we figure out better way how to prevent duplicates

MET-1066 put back indexing to global indices

---

ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/RareDiseaseChangeLogXlsExporter.groovy

very irritating mistake with big consequences

ODA-833 fix misaligned columns due to size/size() groovy behaviour

---

ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/publishing/FinalizationChain.groovy

fixed the problem where all external dependencies were considered invalid

ODA-1157 unable to finalize model

---

ModelCatalogueElasticSearchPlugin/grails-app/services/org/modelcatalogue/core/elasticsearch/ElasticSearchService.groovy

setting batch delays for elasticsearch

---

ModelCatalogueCorePlugin/grails-app/services/org/modelcatalogue/core/RelationshipService.groovy

delete the right relationships on the right instance when the based on relationship is removed

MET-1119 base on fixes

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/catalogueElementView.coffee

easy to fix hard to find :metal:

Custom metadata can have now key only

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/changes/changes.coffee
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/b/ChangesSpec.groovy

while running with more functional specs

make changes spec more reliable

---

ModelCatalogueCorePlugin/grails-app/controllers/org/modelcatalogue/core/DataClassController.groovy
ModelCatalogueCorePlugin/grails-app/services/org/modelcatalogue/core/DataClassService.groovy
ModelCatalogueCorePlugin/grails-app/services/org/modelcatalogue/core/PerformanceUtilService.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/export/inventory/DataModelToDocxExporter.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/export/inventory/DocxSpecificationDataHelper.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/publishing/changelog/ChangeLogDocxGenerator.groovy
ModelCatalogueCorePlugin/test/integration/org/modelcatalogue/core/publishing/changelog/ChangeLogDocxGeneratorSpec.groovy
ModelCatalogueCorePluginTestApp/grails-app/conf/BootStrap.groovy
ModelCatalogueCorePluginTestApp/grails-app/conf/BuildConfig.groovy
ModelCatalogueCorePluginTestApp/grails-app/conf/Config.groovy
ModelCatalogueCorePluginTestApp/grails-app/conf/DataSource.groovy
ModelCatalogueCorePluginTestApp/test/integration/org/modelcatalogue/gel/export/AbstractDataModelExporterSpec.groovy
ModelCatalogueCorePluginTestApp/test/integration/org/modelcatalogue/gel/export/AbstractRareDiseasesExporterSpec.groovy
ModelCatalogueCorePluginTestApp/test/integration/org/modelcatalogue/gel/export/DataModelChangeLogXlsExporterSpec.groovy
ModelCatalogueCorePluginTestApp/test/integration/org/modelcatalogue/gel/export/RareDiseaseEligibilityChangeLogXlsExporterSpec.groovy
ModelCatalogueCorePluginTestApp/test/integration/org/modelcatalogue/gel/export/RareDiseasePhenotypeChangeLogXlsExporterSpec.groovy
ModelCatalogueGenomicsPlugin/grails-app/controllers/org/modelcatalogue/core/genomics/GenomicsController.groovy
ModelCatalogueGenomicsPlugin/grails-app/services/org/modelcatalogue/gel/GenomicsService.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/DataModelChangeLogXlsExporter.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/RareDiseaseChangeLogXlsExporter.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/RareDiseaseEligibilityChangeLogXlsExporter.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/RareDiseasePhenotypeChangeLogXlsExporter.groovy
setup-frontend.sh

The new PerformanceUtilService is plugged into DataClassService and GenomicsService

Feature optimise rd rchangelog eports

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/metadata-editor/templates/metadataEditor.tpl.html
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/metadataEditor.coffee

MET-1152 do not add metadata automatically

---

ModelCatalogueCorePluginTestApp/test/integration/org/modelcatalogue/gel/export/AbstractDataModelExporterSpec.groovy
ModelCatalogueCorePluginTestApp/test/integration/org/modelcatalogue/gel/export/DataModelChangeLogXlsExporterSpec.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/DataModelChangeLogXlsExporter.groovy
ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/RareDiseaseChangeLogXlsExporter.groovy

hierarchy fix & cope with zero dataclasses 
Just realised I've created pull request prematurely. I have a failing test to fix.

ODA-1455 & ODA-1457 fixes for GEL xls Changelogs

---

ModelCatalogueGenomicsPlugin/src/groovy/org/modelcatalogue/gel/export/DataModelChangeLogXlsExporter.groovy

the DataModel option didn't support multiple top level dataClasses

fix GELChangelog xls - enable multiple top level dataclasses

---

ModelCatalogueCorePlugin/grails-app/domain/org/modelcatalogue/core/DataModel.groovy

MET-975 fixed some transient object errors

---

ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/BatchAndActionsSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/ChangesSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/DataClassWizardSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/DataModelWizardSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/DataTypeWizardSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/MeasurementUnitWizardSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/geb/AbstractModelCatalogueGebSpec.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/geb/Common.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/geb/Keywords.groovy

Reverts MetadataRegistry/ModelCataloguePlugin#739

Revert "autoclose messages instead of waiting to disappear"

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/navigationRightActions.coffee

prompt first before generating the asset

MET-1121 better logging

---

ModelCatalogueCorePluginTestApp/test/integration/org/modelcatalogue/core/elasticsearch/ElasticSearchServiceSpec.groovy
ModelCatalogueElasticSearchPlugin/grails-app/services/org/modelcatalogue/core/elasticsearch/ElasticSearchService.groovy
ModelCatalogueElasticSearchPlugin/src/groovy/org/modelcatalogue/core/elasticsearch/CatalogueElementDocumentSerializer.groovy

date detection disabled
not putting the id to the document
do not reinitialize the client after each spec

improved elasticsearch indexing and mapping

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/detail-sections/templates/customMetadata.tpl.html
ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/detail-sections/templates/dataType.tpl.html
ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/detail-sections/templates/enumerations.tpl.html
ModelCatalogueFormsPlugin/grails-app/assets/javascripts/mc/core/forms/templates/formGrid.tpl.html
ModelCatalogueFormsPlugin/grails-app/assets/javascripts/mc/core/forms/templates/formItem.tpl.html
ModelCatalogueFormsPlugin/grails-app/assets/javascripts/mc/core/forms/templates/formMetadata.tpl.html
ModelCatalogueFormsPlugin/grails-app/assets/javascripts/mc/core/forms/templates/formSection.tpl.html

@musketyr The best you can do before vacation is to merge strange code 😎

Met 1138 table stripes

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/templates/infiniteTable.tpl.html
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/detailSections.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/infiniteTable.coffee

Wait with merge until @amilward give us his opinion... https://metadata.atlassian.net/browse/MET-1170

load 10 items by default

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/catalogueElementEnhancer.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/catalogueElementActions.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/index.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/modals/modalPromptCloneIntoDataModel.coffee
ModelCatalogueElasticSearchPlugin/src/groovy/org/modelcatalogue/core/elasticsearch/ElasticSearchQueryList.groovy

when cloning elements into data model

MET-961 warn about data models might be imported

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/catalogueElementView.coffee

after logging out from data model tree view.
removed couple of no longer necessary event listeners

MET-1183 user prompt for login

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/actions.coffee

and the user tries to fix the error

MET-1190 save is no longer disabled when error happens

---

ModelCatalogueElasticSearchPlugin/grails-app/services/org/modelcatalogue/core/elasticsearch/ElasticSearchService.groovy

as there are tons of them live and having them indexed actually messes up the user experience

MET-1113 skip deprecated data models

---

ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/util/builder/CatalogueElementProxyRepository.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/xml/CatalogueElementPrintHelper.groovy

included id even for repeated occurrences of the element
ingoring self-references during import

MET-1191 xml fails to include id

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/templates/dataModelWizard.tpl.html

Friday melancholy:
"If you want to build big company, build yourself first!", Tomas Bata :-)

Met 912 enhance texts

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/navigationRightActions.coffee
ModelCatalogueCorePluginTestApp/grails-app/conf/BootStrap.groovy
ModelCatalogueCorePluginTestApp/grails-app/views/index.gsp
ModelCatalogueSpringSecurity2xPlugin/grails-app/services/org/modelcatalogue/core/security/ss2x/SpringSecurity2SecurityService.groovy

super user called "supervisor" (same password for dev) is the only person which can view monitoring, user management and console plugin

MET-1206 super user

---

ModelCatalogueCorePluginTestApp/grails-app/views/index.gsp

instead of showing the flash message in the fixed HTML view, it calls the messages service

MET-1222 flash message sticks with the view

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/catalogueElementPicker.coffee
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/geb/FormFiller.groovy
ModelCatalogueCorePluginTestApp/test/integration/org/modelcatalogue/core/elasticsearch/ElasticSearchServiceSpec.groovy
ModelCatalogueElasticSearchPlugin/grails-app/conf/BuildConfig.groovy
ModelCatalogueElasticSearchPlugin/grails-app/services/org/modelcatalogue/core/elasticsearch/ElasticSearchService.groovy
ModelCatalogueElasticSearchPlugin/src/groovy/org/modelcatalogue/core/elasticsearch/ElasticSearchQueryList.groovy
bin/test.sh

required reindexing the servers

MET-1199 upgraded to latest Elasticsearch

---

ModelCatalogueCorePlugin/grails-app/services/org/modelcatalogue/core/security/UserService.groovy
ModelCatalogueCorePluginTestApp/grails-app/conf/BootStrap.groovy
ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/security/RegisterController.groovy

this is also kinf of ping that the new instance is ready

MET-1206 invite supervisor to new instance

---

ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/security/RegisterController.groovy

send personalized email to admin about new user creation

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/modals/modalPromptEnumeratedTypeEdit.coffee

while editing from the table view

MET-1193 missing name in edit data type modal

---

ModelCatalogueCorePlugin/grails-app/conf/BuildConfig.groovy

(set border to merged cells fix)

upgraded spredsheet builder to latest release

---

ModelCatalogueCorePluginTestApp/grails-app/views/register/forgotPassword.gsp

emphasizes that you fill in also email not just username

MET-1195 forgotten username

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/modals/templates/dataClassWizard.tpl.html
ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/templates/dataModelWizard.tpl.html
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/dataClassWizard.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/dataModelWizard.coffee
ModelCatalogueCorePlugin/grails-app/controllers/org/modelcatalogue/core/AbstractCatalogueElementController.groovy
ModelCatalogueCorePlugin/src/groovy/org/modelcatalogue/core/policy/UniqueChecker.groovy
ModelCatalogueCorePluginTestApp/console-scripts/addUniqueOfKind.groovy
ModelCatalogueCorePluginTestApp/grails-app/conf/BootStrap.groovy
ModelCatalogueCorePluginTestApp/test/functional/org/modelcatalogue/core/DataClassWizardSpec.groovy

the Unique of Kind Data Model Policy is applied automatically on any existing data model, new data models has this policy prefilled

MET-1273 duplicate names within data model

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/listEnhancer.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/infiniteListCtrl.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/ui/infiniteTable.coffee

and generally all manually load tables

MET-1255 fixed loading of data elements in data class

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/listEnhancer.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/core/listReferenceEnhancer.coffee
ModelCatalogueCorePlugin/grails-app/assets/javascripts/modelcatalogue/util/rest.coffee

if more than one call to same URL requested `rest` service with the flag `join` only one backend call is made as one promise is reused for every similar call

MET-1261 container responsiveness

---

ModelCatalogueCorePlugin/grails-app/assets/javascripts/mc/core/ui/detail-sections/templates/dataType.tpl.html
ModelCatalogueCorePlugin/grails-app/controllers/org/modelcatalogue/core/EnumeratedTypeController.groovy

…ized as lists
thanks to week condition for finding out if the item is list or not

MET-1245 deprecated enumeration red in data type detail section and as tree node

---

ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/security/RegisterController.groovy

found live, missing property in controller

MET-1327 problem with registration

---

ModelCatalogueCorePluginTestApp/grails-app/conf/BootStrap.groovy
ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/DataImportController.groovy
ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/elasticsearch/ElasticSearchService.groovy
ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/forms/ModelToFormExporterService.groovy
ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/elasticsearch/ElasticSearchQueryList.groovy
ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/util/builder/DefaultCatalogueElementProxy.groovy
bin/run/dev.sh

Reverts MetadataConsulting/ModelCataloguePlugin#881

Revert "MET-1337 changes needed to generate the required forms"

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/catalogueElementActions.coffee
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/navigationRightActions.coffee
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/catalogueElementView.coffee
ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/AbstractCatalogueElementController.groovy

with power comes responsibility - use with care

supervisor can edit finalized

---

ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/util/builder/DefaultCatalogueElementProxy.groovy

to prevent ConcurrentModificationException

MET-1352 defensive copies for catalogue builder

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/mc/core/ui/templates/dataModelWizard.tpl.html

when name of the data model is too long

MET-1355 disable the create button

---

setup-frontend.sh

nvm try to use the version demanded too soon

running nvm installation in "try-catch" block

---

ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/DataModelController.groovy

as it was trying to fetch the count of data elements and data types using the mysql stored function

the data model controller failed in development

---

ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/mysql-procedures.sql

in stored procedures finding all destination

check for processed catalogue elements

---

ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/mysql-procedures.sql

improved getting the used data elements and data types for rare diseases conditions by ~30 second

improvement in getting used data elements

---

ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/ElementService.groovy
ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/InitCatalogueService.groovy
ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/util/builder/DefaultCatalogueElementProxy.groovy

fixed the problem with QueryException and missing property enumerations on DataType class

MET-1393 catalogue builder fixes

---

ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/elasticsearch/ElasticSearchService.groovy

fixes the problem with hanging draft creation

ignoring attempts to index nulls

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/mc/core/ui/templates/propertiesPane.tpl.html
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/propertiesPane.coffee
ModelCatalogueCorePluginTestApp/grails-app/conf/mc-config.groovy.example
docs/development/shell.md

MET-1404 Properties pane is now able to display extensionValues

---

ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/export/inventory/CatalogueElementToXlsxExporter.groovy

https://github.com/MetadataConsulting/spreadsheet-builder/issues/15

temporary disable adding semantic version as comment to data type cells

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/modals/modalPromptNewCatalogueXmlImport.coffee
ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/DataImportController.groovy
ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/audit/AuditService.groovy

each xml file will be evaluated separately in the order they were written in the archive file (usually alphabetical order) so you should prefix the xml files with numbers if you create the archive manually)

MET-1393 ability to import zip file with xml

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/mc/core/ui/states/templates/dataModels.tpl.html
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/states/controllers/DataModelsCtrl.coffee
ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/CatalogueController.groovy

clinical tags are now ignored and the preload is shown even there are an existing data model and the name of the data model is Clinical Tags

MET-1411 preload never shown as clinical tags are always present

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/mc/core/ui/states/templates/dataModels.tpl.html
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/states/controllers/DataModelsCtrl.coffee

as the page refreshes too early

MET-1428 cannot search

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/modals/modalPromptDataModelPolicyEdit.coffee
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/catalogueElementPicker.coffee

only admins can create data model policies
Create New not shown in catalogue element picker for data model policies for curators

MET-1444 create data model policy

---

ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/elasticsearch/ElasticSearchService.groovy

made the search term lower case so there is no unexpected difference in results.

MET-1450 elasticsearch responds differently on different cases

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/navigationRightActions.coffee

Changed the message to Import MC (as DSL file) so now it looks more like the name of the action in the menu.

Changed message of Import MC action

---

ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/policy/UniqueChecker.groovy

make UniqueChecker proof to working with not-yet-saved DataModel

MET-1460 user cannot populate metadata

---

ModelCatalogueCorePluginTestApp/grails-app/domain/org/modelcatalogue/core/Tag.groovy

I have removed the versionNumber constraint in the Tag class - as it seems to be causing a problem across models in the Test Server

Removed versionNumber constraint

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/changes/changes.coffee
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/catalogueElementProperties.coffee
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/states/controllers/DataModelTreeCtrl.coffee
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/util/names.coffee
ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/DataClassController.groovy
ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/DataModelController.groovy
ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/forms/FormGeneratorController.groovy
ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/AssetService.groovy
ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/export/inventory/CatalogueElementToXlsxExporter.groovy
ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/export/inventory/DataClassToDocxExporter.groovy
ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/gel/GelJsonExporter.groovy
ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/gel/export/RareDiseasesDocExporter.groovy

Preliminary documentation and trying to understand Catalogue Element to Xlsx Exporter.

MET-1779 documentation of inventory report- preliminary

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/batchView.coffee

show last updated of batch along with date created

MET-1684 show last updated of batch

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/actions.coffee
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/catalogueElementActions.coffee
ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/util/ui/actions.coffee

INFINITE_LIST was called INIFINITE_LIST

corrected typo

---

ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/CatalogueController.groovy
ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/xml/CatalogueElementPrintHelper.groovy
ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/xml/DataTypePrintHelper.groovy

Making XML export more verbose by default - so that we can use the export in xslts to generate schemas

Xml export

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/catalogueElementActions.coffee
ModelCatalogueCorePluginTestApp/grails-app/controllers/org/modelcatalogue/core/UserController.groovy
ModelCatalogueCorePluginTestApp/grails-app/domain/org/modelcatalogue/core/security/User.groovy
ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/ModelCatalogueSecurityService.groovy
ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/security/UserService.groovy
ModelCatalogueCorePluginTestApp/grails-app/services/org/modelcatalogue/core/security/ss2x/SpringSecurity2SecurityService.groovy
ModelCatalogueCorePluginTestApp/grails-app/utils/org/modelcatalogue/core/security/ApiKeyUtils.groovy
ModelCatalogueCorePluginTestApp/src/groovy/org/modelcatalogue/core/SecurityService.groovy

Fixes: https://metadata.atlassian.net/browse/MET-2033

Add API Key directly in cURL Command

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/templates/mc/core/ui/modals/modalValidationRuleEdit.tpl.html

Fixes https://metadata.atlassian.net/browse/MET-1994?jql=status%20%3D%20Open%20AND%20labels%20%3D%20North_Thames

Fix spelling error

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/modals/modalPromptCsvHeaders.coffee

Fixes https://metadata.atlassian.net/browse/MET-2007
I have added a cancel button:

Add cancel button

---

ModelCatalogueCorePluginTestApp/test/integration/org/modelcatalogue/core/audit/AuditingIntegrationSpec.groovy

The test passes if the user is not logged 
Fixes https://metadata.atlassian.net/browse/MET-2117

Fixes MET-2117 broken test 

---

ModelCatalogueCorePluginTestApp/grails-app/domain/org/modelcatalogue/core/CatalogueElement.groovy
ModelCatalogueCorePluginTestApp/test/unit/org/modelcatalogue/core/DataModelDomainSpec.groovy

See: https://metadata.atlassian.net/browse/MET-1355

Rewrite name and description constraints tests

---

ModelCatalogueCorePluginTestApp/grails-app/assets/stylesheets/modelcatalogue/core/ui/bs/directives.less

See: https://metadata.atlassian.net/browse/MET-1857

30px height of input to fix issues with select

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/actions.coffee

See: https://metadata.atlassian.net/browse/MET-1661

Fix grammar error

---

ModelCatalogueCorePluginTestApp/grails-app/domain/org/modelcatalogue/core/security/User.groovy

See: https://metadata.atlassian.net/browse/MET-1537

add unique constraint to user email

---

ModelCatalogueCorePluginTestApp/grails-app/assets/javascripts/modelcatalogue/core/ui/bs/catalogueElementActions.coffee
ModelCatalogueCorePluginTestApp/grails-app/conf/BootStrap.groovy

See: https://metadata.atlassian.net/browse/MET-1843

Show text when the use hovers the download asset button
